





const screen = document.getElementById("calculator");
const buttons = document.querySelectorAll('.numbers');
const operators = document.querySelectorAll('.operator');



let memory="";
let operator ="";
let firstOperand = "";
let secondOperand = "";

buttons.forEach((buttonNr) =>
buttonNr.addEventListener('click',typeNumbers)
);

function typeNumbers(e){
    let numberSelection = e.target.textContent;
    firstOperand = numberSelection;
    screen.value+=firstOperand;
    }
    


function calculate(firstOperand, secondOperand, operator) {
    if (operator === '+') {
      return firstOperand + secondOperand;
    } else if (operator === '-') {
      return firstOperand - secondOperand;
    } else if (operator === '*') {
      return firstOperand * secondOperand;
    } else if (operator === '/') {
      return firstOperand / secondOperand;
    }
    return secondOperand;
}
